<a href="https://colab.research.google.com/github/Fuad3004/Beggining-of-Machine-Learning-Using-PyTorch/blob/main/fuad_pytorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Import

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.0.0+cu118


#SCALER VECTOR

Creating Tensor

Pytorch Tensor ---->>> https://pytorch.org/docs/stable/tensors.html


In [ ]:
#scaler
scalar=torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#get tensor bask as python int
scalar.item()

7

In [ ]:
#vector
vector=torch.tensor([7,7])
vector 

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

#MATRIX

In [ ]:
#MATRIX

MATRIX = torch.tensor([[7,8], [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX[1,1]

tensor(10)

#TENSOR


In [ ]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim


3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0] #indexing

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [ ]:
TENSOR2=torch.tensor([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
TENSOR2


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
TENSOR2.shape

torch.Size([3, 3])

In [ ]:
TENSOR2.item

<function Tensor.item>


#Random tensors

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...

In [ ]:
#Ramdom Tensors
random_tensor= torch.rand(3,4)
random_tensor


tensor([[0.5747, 0.1466, 0.0230, 0.8191],
        [0.7258, 0.7016, 0.6857, 0.9007],
        [0.0667, 0.6095, 0.4999, 0.0963]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor[0]

tensor([0.5747, 0.1466, 0.0230, 0.8191])

In [ ]:
random_tensor2=torch.rand(3,10,2)
random_tensor2

tensor([[[0.5164, 0.4108],
         [0.0310, 0.3770],
         [0.5461, 0.0256],
         [0.7394, 0.4028],
         [0.0893, 0.2233],
         [0.3095, 0.5062],
         [0.5673, 0.7122],
         [0.3402, 0.9813],
         [0.5067, 0.0453],
         [0.9053, 0.3488]],

        [[0.6839, 0.4011],
         [0.5195, 0.9477],
         [0.9664, 0.9561],
         [0.4043, 0.8070],
         [0.0641, 0.2238],
         [0.9114, 0.3668],
         [0.0340, 0.2251],
         [0.7576, 0.1723],
         [0.1626, 0.6955],
         [0.9111, 0.4900]],

        [[0.4112, 0.3171],
         [0.8019, 0.6041],
         [0.9768, 0.2952],
         [0.3858, 0.0725],
         [0.5509, 0.1251],
         [0.3129, 0.4431],
         [0.7349, 0.6230],
         [0.0829, 0.0212],
         [0.7974, 0.5669],
         [0.9900, 0.9365]]])

In [ ]:
random_tensor2.shape

torch.Size([3, 10, 2])

#Zeros and Ones

In [ ]:
Zeros=torch.zeros(3,4)
Zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
Zeros.dtype

torch.float32

In [ ]:
ones=torch.ones(2,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

#Creating a range and tensors like


In [ ]:
torch.range(0,10)

<ipython-input-129-dfdec9b83f7d>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
 a=torch.arange(start=1, end=100, step=5)

In [ ]:
#creating tensors like

ten_zeros= torch.zeros_like(input=a)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#Tensor Datatypes

In [ ]:
float_32_tensor= torch.tensor([3.0,6.0,9.0], dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype #default is float

torch.float32

In [ ]:
float_16_tensor= torch.tensor([3.0,6.0,9.0], dtype=torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor.dtype 

torch.float16

**NOTE** : Tensor datatypes is one of the 3 bigg errors you will run into with PyTorch & Deep learning.
1. Tensors are not right datatype......
2. Tensor are in not right shape
3. Tensors not on the right device

In [ ]:
float_tensor=torch.tensor([3.0,6.0,9.0], 
                          dtype=None,
                          device=None, #cpu or gpu set korte parbo.cpu hole device="cpu"...gpu hole device="cuda",
                          requires_grad=False) #wheather or not to track gradients with this tensors operations
float_tensor

tensor([3., 6., 9.])

In [ ]:
float_tensor.dtype

torch.float32

#Datatype conversion




In [ ]:
float_16=float_32_tensor.type(torch.float16)

In [ ]:
float_16.dtype

torch.float16

In [ ]:
float_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
another=torch.tensor([3,6,9], dtype=torch.long)

In [ ]:
another

tensor([3, 6, 9])

In [ ]:
float_32_tensor * another


tensor([ 9., 36., 81.])

#Getting information from tensors

**NOTE** : Tensor datatypes is one of the 3 bigg errors you will run into with PyTorch & Deep learning.
1. Tensors are not right datatype......for this we can check tensor.dtype
2. Tensor are in not right shape........we can use tensor.shape
3. Tensors not on the right device........ we can use tensor.device 

In [ ]:
#create a tensor
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.8589, 0.3378, 0.0059, 0.2630],
        [0.6401, 0.8144, 0.3612, 0.8151],
        [0.7251, 0.9677, 0.1768, 0.2126]])

In [ ]:
some_tensor.size(), some_tensor.shape      #duita e same ashe whatever i want I can use but .shape is more preferable 

(torch.Size([3, 4]), torch.Size([3, 4]))

In [ ]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.size()}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on {some_tensor.device}")

tensor([[0.8589, 0.3378, 0.0059, 0.2630],
        [0.6401, 0.8144, 0.3612, 0.8151],
        [0.7251, 0.9677, 0.1768, 0.2126]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Shape of tensor: torch.Size([3, 4])
Device tensor is on cpu


In [ ]:
#excercise

In [ ]:
exercise=torch.rand(4,5)
exercise

tensor([[0.3254, 0.8724, 0.9633, 0.5420, 0.5213],
        [0.1031, 0.6045, 0.7802, 0.7148, 0.9816],
        [0.8643, 0.6884, 0.8394, 0.0155, 0.0179],
        [0.6890, 0.5938, 0.4136, 0.3543, 0.7695]])

In [ ]:
print(f"datatype of exercise is {exercise.dtype}")
print(f"shape of the tensor {exercise.shape}")
print(f"device of the tensor {exercise.device}")

datatype of exercise is torch.float32
shape of the tensor torch.Size([4, 5])
device of the tensor cpu


In [ ]:
exercise16 = exercise.type(torch.float16)
exercise16.dtype

torch.float16

#Manipulating Tensors (tensons operations)
1.   Addition
2.   Subtraction

1.   Multiplication (Element wise)

1.   Matrix Multiplication
2.   Division





In [ ]:
tensor= torch.tensor([1,2,3]) #Addition 10 with each element
tensor+10

tensor([11, 12, 13])

In [ ]:
tensor*10

tensor([10, 20, 30])

In [ ]:
tensor-10

tensor([-9, -8, -7])

In [ ]:
#try out inbuilt function
torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor,2)


tensor([3, 4, 5])

# Matrix multiplication:

Two ways:
1. Elements-wise multiplication
2. Matrix multiplication(dot product)


In [ ]:
#Element wise multiplication

print(tensor,"*", tensor)
print(f"Equals:{tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [ ]:
#matrix wise multiplication


torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
tensor@tensor #we are not using it!

tensor(14)

In [ ]:
%%time
value=0
for i in range (len(tensor)):
   value+= tensor[i]*tensor[i]
print(value)  # to see who is fast

tensor(14)
CPU times: user 1.74 ms, sys: 0 ns, total: 1.74 ms
Wall time: 2.14 ms


In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 78 µs, sys: 0 ns, total: 78 µs
Wall time: 82.7 µs


tensor(14)

**one of the most common error in deep learning that is shape error**
two rules must match


1.   The **inner dimensions** must match:
    
     


*   (3,2) @ (3,2) wont work
*   (2,3) @ (3,2) will work




2.   the resulting matrix has the shape of **the outer dimensions**
    **bold text**





#Transpose Matrix

To ignore shape issues we can manipulate the shape of our tesnor using a **transpose**
(3,2) @ (3,2) wont work so we need to transpose the matrix

In [ ]:
A=torch.rand(3,2)
B=torch.rand(3,2)

In [ ]:
torch.matmul(A,B.T)

tensor([[0.6212, 0.7137, 1.3426],
        [0.5107, 0.5932, 1.1438],
        [0.4151, 0.5259, 1.2023]])

In [ ]:
B

tensor([[0.5552, 0.2572],
        [0.5762, 0.3635],
        [0.8153, 0.9795]])

In [ ]:
B.T

tensor([[0.5552, 0.5762, 0.8153],
        [0.2572, 0.3635, 0.9795]])

#Tensor Aggregation

finding the min, mean, max, sum etc from tensors.



1.   variable.max() or torch.max(variable).......>>>>max pabo
2.   variable.min() or torch.min(variable).......>>>>min pabo similar shob



In [ ]:
x=torch.randn(5,50,3)

In [ ]:
x.dtype


torch.float32

In [ ]:
torch.mean(x)

tensor(0.0029)

In [ ]:
torch.mean(x.type(torch.float32)) #the torch.mean() function requiers a tensor of float32 datatype to work

tensor(0.0029)

In [ ]:
x.type(torch.float32).mean()

tensor(0.0029)

**Finding the position of the min and max**

In [ ]:
x

tensor([[[-1.0709e+00,  1.1601e+00, -2.7641e-01],
         [ 2.3819e-01, -1.4876e+00, -2.8143e+00],
         [-2.6556e-01,  1.3202e+00, -7.2998e-01],
         [ 7.6230e-01,  5.5247e-02,  7.9078e-01],
         [ 1.1954e+00,  5.6018e-01, -2.4823e-01],
         [-5.9831e-01, -1.1727e+00, -3.5475e-01],
         [ 9.5029e-01, -1.8517e-01,  4.4968e-01],
         [ 9.9420e-01,  5.7450e-03, -1.4382e+00],
         [ 1.0013e-01, -2.6673e-01, -1.1075e+00],
         [-1.5833e+00,  1.2938e+00,  1.0312e+00],
         [-9.9127e-01, -7.3284e-01,  6.4169e-01],
         [ 1.2403e+00,  1.3699e+00, -1.7836e+00],
         [ 1.1333e+00,  1.3744e+00,  9.2026e-01],
         [-4.6976e-01, -2.5639e-01,  2.8350e-01],
         [ 8.6529e-01,  6.3776e-01, -1.4576e+00],
         [-1.1870e+00,  3.4955e-01,  8.9165e-01],
         [ 4.3787e-02,  9.0937e-02,  1.1095e+00],
         [ 8.0539e-02,  3.6853e-01,  1.1834e+00],
         [ 1.5352e+00,  1.1370e-01,  1.5752e+00],
         [ 7.9082e-01,  2.3558e-01, -7.5229e-01],


In [ ]:
x.argmin() # find the position in tensor that has the minimum value with "argmin()" function..> return index position

tensor(440)

In [ ]:
x[0]

tensor([[-1.0709e+00,  1.1601e+00, -2.7641e-01],
        [ 2.3819e-01, -1.4876e+00, -2.8143e+00],
        [-2.6556e-01,  1.3202e+00, -7.2998e-01],
        [ 7.6230e-01,  5.5247e-02,  7.9078e-01],
        [ 1.1954e+00,  5.6018e-01, -2.4823e-01],
        [-5.9831e-01, -1.1727e+00, -3.5475e-01],
        [ 9.5029e-01, -1.8517e-01,  4.4968e-01],
        [ 9.9420e-01,  5.7450e-03, -1.4382e+00],
        [ 1.0013e-01, -2.6673e-01, -1.1075e+00],
        [-1.5833e+00,  1.2938e+00,  1.0312e+00],
        [-9.9127e-01, -7.3284e-01,  6.4169e-01],
        [ 1.2403e+00,  1.3699e+00, -1.7836e+00],
        [ 1.1333e+00,  1.3744e+00,  9.2026e-01],
        [-4.6976e-01, -2.5639e-01,  2.8350e-01],
        [ 8.6529e-01,  6.3776e-01, -1.4576e+00],
        [-1.1870e+00,  3.4955e-01,  8.9165e-01],
        [ 4.3787e-02,  9.0937e-02,  1.1095e+00],
        [ 8.0539e-02,  3.6853e-01,  1.1834e+00],
        [ 1.5352e+00,  1.1370e-01,  1.5752e+00],
        [ 7.9082e-01,  2.3558e-01, -7.5229e-01],
        [-3.7217e-01

In [ ]:
x.argmax()

tensor(151)

#Reshaping, Viewing and stacking

*Reshaping- reshapes an input tensor to a defined shape

---


*View- Return a view of an input tensor of a certain shape but keep the same memory as the original tensor

---


*stacking-- combine mulitiple tensors on top of each other (vstack)-vertical stack or side by side (hstack) horizontal stack


---


*squeeze- removes all 1 Dimenstion from a tensor

---


*unsqueeze- add a 1 dimension to a target tensor

---


*Permute- return a view of the input with dimensions permuted(swapped) in a certain way


In [ ]:
import torch
x=torch.arange(1.,10.)
x, x.shape


(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_reshaped=x.reshape(1,7)
x_reshaped #size same nei tai hobe na, size chilo 9, amra dilam 1,7 then eta hobe na #this error is for understanding

RuntimeError: ignored

In [ ]:
x_reshaped=x.reshape(1,9)
x_reshaped

tensor([[7., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_reshaped=x.reshape(2,9) # size 18 hoy
x_reshaped #this error is for understanding

RuntimeError: ignored

In [ ]:
x_reshaped=x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
x_reshaped=x.reshape(3,3) #3 *3=9 tai
x_reshaped

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

#Change the view

In [ ]:
z=x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#z ar x same. Changing z changes x because a view of  a tensor shared the same memory as the original

z[:,0]=7 #1st element k target korse index 1 k change korbe baki gula ager moto arange() kaj korbe 
z,x

(tensor([[7., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([7., 2., 3., 4., 5., 6., 7., 8., 9.]))

#Stack tensors on top of each other

In [ ]:

x_stacked= torch.stack([x, x, x, x], dim=0)
x_stacked
#vertically pelam

tensor([[7., 2., 3., 4., 5., 6., 7., 8., 9.],
        [7., 2., 3., 4., 5., 6., 7., 8., 9.],
        [7., 2., 3., 4., 5., 6., 7., 8., 9.],
        [7., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
#stack tensors on top of each other
x_stacked= torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[7., 7., 7., 7.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

#Squeeze
Returns a tensor with all specified dimensions of input of size 1 removed.



In [ ]:
 q=torch.arange(1.,9)
 p=q.reshape(8,1)
 p,p.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.]]),
 torch.Size([8, 1]))

In [ ]:
print(f"previoous tensor: {p}")
print(f"previous shape:{p.shape}")
#removing extra dimensions from p
p_squeezed=p.squeeze()
print(f"new tensos:{p_squeezed}")
print(f"New shape:{p_squeezed.shape}")

previoous tensor: tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.]])
previous shape:torch.Size([8, 1])
new tensos:tensor([1., 2., 3., 4., 5., 6., 7., 8.])
New shape:torch.Size([8])


In [ ]:
print(f"previoous tensor: {p_squeezed}")
print(f"previous shape:{p_squeezed}")

p_unsqueezed=p.unsqueeze(dim=1)
print(f"new tensos:{p_unsqueezed}")
print(f"New shape:{p_unsqueezed.shape}")

previoous tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8.])
previous shape:tensor([1., 2., 3., 4., 5., 6., 7., 8.])
new tensos:tensor([[[1.]],

        [[2.]],

        [[3.]],

        [[4.]],

        [[5.]],

        [[6.]],

        [[7.]],

        [[8.]]])
New shape:torch.Size([8, 1, 1])


In [ ]:
print(f"previoous tensor: {p_squeezed}")
print(f"previous shape:{p_squeezed.shape}")
#unsqueeze te dimension is mustttttttt
#add an extra dimension with unsqueeze
p_unsqueezed=p.unsqueeze(dim=0)
print(f"new tensos:{p_unsqueezed}")
print(f"New shape:{p_unsqueezed.shape}")

previoous tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8.])
previous shape:torch.Size([8])
new tensos:tensor([[[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.]]])
New shape:torch.Size([1, 8, 1])


In [ ]:
print(f"previoous tensor: {p_squeezed}")
print(f"previous shape:{p_squeezed.shape}")
#unsqueeze te dimension is mustttttttt
#add an extra dimension with unsqueeze
p_unsqueezed=p.unsqueeze(dim=1)
print(f"new tensos:{p_unsqueezed}")
print(f"New shape:{p_unsqueezed.shape}")

previoous tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8.])
previous shape:torch.Size([8])
new tensos:tensor([[[1.]],

        [[2.]],

        [[3.]],

        [[4.]],

        [[5.]],

        [[6.]],

        [[7.]],

        [[8.]]])
New shape:torch.Size([8, 1, 1])


#Permute
torch.permute - rearrange the dimensions of a  target tensor in a specified order

In [ ]:
e=torch.rand(size=(224,224,4)) #height, width, color_chanels>rgb

e

tensor([[[0.5609, 0.6146, 0.8183, 0.7102],
         [0.1790, 0.0252, 0.0704, 0.0823],
         [0.4287, 0.7099, 0.6111, 0.5480],
         ...,
         [0.0275, 0.8692, 0.4003, 0.4954],
         [0.6623, 0.2633, 0.8249, 0.2236],
         [0.7869, 0.0282, 0.6458, 0.2152]],

        [[0.7261, 0.3689, 0.5348, 0.1968],
         [0.9641, 0.7528, 0.9822, 0.1342],
         [0.9237, 0.8159, 0.9548, 0.4691],
         ...,
         [0.9640, 0.4790, 0.0097, 0.8960],
         [0.2922, 0.0384, 0.9384, 0.4142],
         [0.6834, 0.9657, 0.4116, 0.3323]],

        [[0.8525, 0.2209, 0.8879, 0.1005],
         [0.4014, 0.0272, 0.1994, 0.5012],
         [0.0513, 0.9324, 0.9001, 0.8508],
         ...,
         [0.5186, 0.5873, 0.7386, 0.7892],
         [0.3753, 0.2618, 0.0785, 0.4493],
         [0.8621, 0.6699, 0.6445, 0.6563]],

        ...,

        [[0.4150, 0.9424, 0.8902, 0.4040],
         [0.2044, 0.8803, 0.1468, 0.6453],
         [0.7823, 0.7305, 0.9386, 0.2069],
         ...,
         [0.8979, 0.8

In [ ]:
#permute the q in different way...we want colorchanel, height, width

e_permuted=e.permute(2, 0, 1)

print(f"previous shape: {e.shape}")
print(f"new shape: {e_permuted.shape}")

previous shape: torch.Size([224, 224, 4])
new shape: torch.Size([4, 224, 224])


In [ ]:
e[:,0,0]

tensor([0.5609, 0.7261, 0.8525, 0.0099, 0.7513, 0.2946, 0.5353, 0.4378, 0.3273,
        0.4844, 0.1599, 0.8605, 0.3444, 0.4255, 0.6404, 0.5917, 0.3983, 0.0051,
        0.3460, 0.7199, 0.7036, 0.2244, 0.5276, 0.4980, 0.6576, 0.2656, 0.8504,
        0.5776, 0.2342, 0.4734, 0.2879, 0.9852, 0.2168, 0.5826, 0.9546, 0.2486,
        0.2972, 0.9470, 0.3560, 0.0426, 0.7441, 0.3253, 0.4073, 0.2831, 0.0456,
        0.5060, 0.4877, 0.6997, 0.0903, 0.8383, 0.0037, 0.3180, 0.7479, 0.5924,
        0.8003, 0.1278, 0.2312, 0.1548, 0.3900, 0.2508, 0.8402, 0.1606, 0.8863,
        0.6369, 0.5246, 0.3847, 0.2362, 0.0376, 0.4576, 0.5184, 0.4378, 0.3801,
        0.2931, 0.2185, 0.4856, 0.6284, 0.1603, 0.6257, 0.4717, 0.8716, 0.0129,
        0.5346, 0.2681, 0.1499, 0.0822, 0.2574, 0.1058, 0.4708, 0.8420, 0.5912,
        0.8197, 0.9385, 0.8170, 0.3127, 0.4406, 0.8687, 0.0465, 0.2359, 0.3918,
        0.6608, 0.0414, 0.8432, 0.5486, 0.1104, 0.3910, 0.3150, 0.0905, 0.7413,
        0.3587, 0.1415, 0.6614, 0.6458, 

In [ ]:
#if we want to change the value

In [ ]:
e[0,0,0]

tensor(0.5609)

In [ ]:
e[0,0,0]=0.1452

In [ ]:
e[0,0,0] #updated

tensor(0.1452)

#Selecting Data from indexing (INDEXING)

same as numpy



In [ ]:
import torch

In [ ]:
index=torch.arange(1,10).reshape(1,3,3)
index, index.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
index[0] #gives us middle tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
index[0,0] #index on middle brackett index[0][0] ebhabeo hobe ...>>> gives us 0th index

tensor([1, 2, 3])

In [ ]:
index[0,0,0] #index on last bracket ......Oth tensor, 0Th index, 0th element

tensor(1)

In [ ]:
index[0][1][1]

tensor(5)

In [ ]:
index[:,0] #you can also use ":" to select all of a targer dimension

tensor([[1, 2, 3]])

In [ ]:
index[:,:,1] #get all values of the 0th and 1st dimensions but only index 1 of 2nd dimension

tensor([[2, 5, 8]])

In [ ]:
#get all values of the 0th and 1st dimensions but only 1 index value of 1st and 2nd dimension
index[:,1,1] #semicolon er jonno 3rd bracket ta ashbe index[0][1][1] ekhane ashbe na

tensor([5])

In [ ]:
#get index 0 of 0th and 1st dimension and all the values of 2nd dimension

index[0,0,:]

tensor([1, 2, 3])

In [ ]:
#find out the value 9

index[0,2,2]

tensor(9)

In [ ]:
#return 3,6,9
index[:,:,2]

tensor([[3, 6, 9]])

#Pytorch Tensors & Numpy
Numpy is popular scientific Python numerical computing library.
and because of this, PyTorch has functionality to interact with it.

1.   Data in Numpy, want in Pytorch tensor..> torch.from_numpy(ndarray)


2.   PyTorch tensor -> NumPy -> torch.Tensor.numoy() 






In [ ]:
import torch
import numpy as np
array= np.arange(1.0, 8.0)
tensor= torch.from_numpy(array)
array, tensor  #numpy er default data type is float64 but tensor e data type float32 ...--> tensor= torch.from_numpy(array).type(torch.float32) likhe dile float e 32 te ashbe

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
  #change the value of array, tensor change hobe na
  array =array+1
  array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
#tensor to numpy array
tensor=torch.ones(7)
numpy_tensor=tensor.numpy() #datatype tensor er default ta ashbe
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
#change the value of tensor
tensor=tensor+1 #change hobe
tensor, numpy_tensor#change hobena

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))